openapi: 3.0.0
info:
  title: Autobuch
  description: "Die Autobuch-App nutzt einen simplen REST-Webservices zur Kommunikation\
    \ mit dem Backend. Dieser ermöglicht die üblichen CRUD-Operationen zur Suche,\
    \ Anzeige, Bearbeitung und Löschung von Autos, wobei jedes Auto aus einer\
    \ Marke, Model, Autotyp, Herstelldatum und einem Status besteht."
  contact:
    name: Dennis Schulmeister-Zimolong
    url: https://www.wpvs.de
    email: dhbw@windows3.de
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.de
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Index
- name: Auto
paths:
  /:
    get:
      tags:
      - Index
      summary: Wurzeladresse des Webservices
      description: Liefert eine HATEOAS-Übersicht aller collections
      operationId: index
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
                x-content-type: application/json

  /car:
    get:
      tags:
      - Auto
      summary: Autos suchen
      description: Suche nach Autos. Gibt eine Liste aller Autos passend zu
        den übergebenen Suchkriterien zurück.
      operationId: search-car
      parameters:
      - name: brand
        in: query
        description: Gesuchte Marke
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: model
        in: query
        description: Gesuchtes Model
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: type
        in: query
        description: Gesuchter Autotyp
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: production_date
        in: query
        description: Gesuchtes Herstelldatum
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status
        in: query
        description: Gesuchter Status
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Car'
                x-content-type: application/json
    post:
      tags:
      - Auto
      summary: Auto anlegen
      description: "Neues Auto anlegen. Speichert das übergebene Auto in der\
        \ Datenbank. Der Wert des Feldes \"_id\" wird dabei ignoriert, da in jedem Fall\
        \ ein neues Auto mit neuer ID angelegt wird."
      operationId: create-car
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        "201":
          description: Created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'

  /car/{id}:
    get:
      tags:
      - Auto
      summary: Auto lesen
      description: Liest ein einzelnes Auto vom Server.
      operationId: get-car
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        "404":
          description: Not Found
    put:
      tags:
      - Auto überschreiben
      summary: ""
      description: "Überschreibt ein vorhandenes Auto auf dem Server. Bis auf die\
        \ ID können alle Felder geändert werden. Der Versuch, die ID zu ändern, wird\
        \ vom Server stillschweigend ignoriert."
      operationId: update-car
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        "404":
          description: Not Found
    patch:
      tags:
      - Einzelne Felder ändern
      summary: Einzelne Autofelder ändern
      description: "Ändert einzelne Felder eines vorhandenen Autos. Zulässig sind\
        \ alle Felder bis auf die ID, da diese nachträglich nicht mehr verändert werden\
        \ darf."
      operationId: patch-car
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Car'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        "404":
          description: Not Found
    delete:
      tags:
      - Auto
      summary: Auto löschen
      description: Löscht ein Auto auf dem Server.
      operationId: delete-car
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found

components:
  schemas:
    HATEOAS_Collection:
      title: HATEOAS-Links einer Collection
      type: object
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Resource:
      title: HATEOAS-Links einer Resource
      type: object
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Link:
      title: HATEOAS-Link
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string

    Car:
      title: Auto
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HATEOAS_Resource'
        _id:
          type: string
        brand:
          type: string
        model:
          type: string
        type:
          type: string
        production_date:
          type: string
        status:
          type: string
      required:
        - brand
        - model
      example:
        _id: "621ff9a936997df5baba746e"
        brand: "Volkswagen"
        model: "Touran"
        type: "Van"
        production_date: "01.07.2021"
        status: "available"
  securitySchemes: {}
